# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  platform :android do
    desc "Build Debug"
    lane :build_debug do
      ionic(
        platform: 'android',
        release: false
      )
    end
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    ionic(
      platform: 'android', # Build your Android Ionic project
      release: false # Build a "Debug" app
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods
    # carthage
  end

  desc "Upgrade the Xcode project to Xcode 8"
  lane :upgrade_xcode_project do
    team_id = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)
    xcodeprojpath = "platforms/ios/MyApp.xcodeproj"
  
    upgrade_super_old_xcode_project(
      path: xcodeprojpath,
      team_id: team_id
    )
  end

  desc "Build Debug"
  lane :build_debug do
    ionic(
      platform: 'ios',
      release: false,
      type: 'development'
    )
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end