name: Build app

on:
  push:
    branches: [main]
  release:
    types: [created]
        
jobs:   
  android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1
        with:
          cordova-version: 8

      - name: Build
        run: |
          ls -la
          ionic cordova build android --prod

  ios:
    runs-on: macos-latest

    steps:
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1
        with:
          cordova-version: 8

      - name: Build
        run: |
          ls -la
          ionic cordova build ios --prod
