name: Build app

on:
  push:
    branches: [main]
  release:
    types: [created]
        
jobs:   
  android:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1

      - name: Build
        run: |
          ionic cordova build android --prod
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: platforms/android/app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@v1

      - name: Build
        run: |
          ionic cordova build ios --prod
          ls -la platforms/ios/*
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: platforms/ios/build/emulator/MyApp.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
